#ifndef _ARCSOFT_WTMODULE_COMMON_
#define _ARCSOFT_WTMODULE_COMMON_

#define MERR_MR_SDK_CHECK_ERROR			        0X090FF1

#define MERR_SSC_ERROR_BASE 0xA0000000
#define MERR_SSC_NOT_ENOUGH_CHESSBOARD (MERR_SSC_ERROR_BASE+1)
#define MERR_SSC_CHESSBOARD_OVERLAPED (MERR_SSC_ERROR_BASE+2)
#define MERR_SSC_CAL_WITH_LARGE_ERROR (MERR_SSC_ERROR_BASE+3)
#define MERR_SSC_SAME_WIDTHHEIGHT (MERR_SSC_ERROR_BASE+4)
#define MERR_SSC_INPUT_ERROR (MERR_SSC_ERROR_BASE+5)
#define MERR_SSC_INVALID_FILE_NAME (MERR_SSC_ERROR_BASE+6)
#define MERR_SSC_UNEQUAL_IMAGE_NUMBERS (MERR_SSC_ERROR_BASE+7)
#define MERR_SSC_FAIL_VERIFICATION (MERR_SSC_ERROR_BASE+8)
#define MERR_SSC_LARGE_ERROR (MERR_SSC_ERROR_BASE+9)
#define MERR_SSC_NULL_POINT (MERR_SSC_ERROR_BASE + 10)
#define MERR_SSC_INVALID_IMAGE_TYPE (MERR_SSC_ERROR_BASE + 11)
#define MERR_SSC_INCORRECT_INPUT_ORDER (MERR_SSC_ERROR_BASE + 12)
#endif